# Generated by Django 3.2.10 on 2021-12-25 12:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
