# Generated by Django 3.2.10 on 2021-12-25 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
