# Generated by Django 3.2.10 on 2022-01-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost_id',
            new_name='blogpost',
        ),
    ]
