# Generated by Django 3.2.10 on 2022-01-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comment_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='user',
        ),
    ]
