# Generated by Django 3.2.10 on 2022-01-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220103_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_id',
            new_name='author',
        ),
    ]
